/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const cn: typeof import('./src/lib/utils').cn
  const generateUniqueKey: typeof import('./src/lib/utils').generateUniqueKey
  const request: typeof import('./src/composables/request').default
}
